tensorboard:
  _target_: pytorch_lightning.loggers.tensorboard.TensorBoardLogger
  save_dir: "."
  name: null
  version: tblog_${hydra:job.name}
  log_graph: False
  default_hp_metric: True
  prefix: ""
